apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-module-6484
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-module-6484
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
